<a href="https://colab.research.google.com/github/ujin2021/tensorflow-Tutorial/blob/master/multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

### 보스턴 집값 예측

In [3]:
# 1. 과거의 데이터 준비
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path)

# 종속변수, 독립변수
idp = boston[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
dp = boston[['medv']]
print(idp.shape, dp.shape)

(506, 13) (506, 1)


In [7]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape = [13])
# Y = tf.keras.layers.Dense(1)(X) 이전 방법
H = tf.keras.layers.Dense(10, activation = 'swish')(X) # 10개의 node, 활성화함수 : swish
Y = tf.keras.layers.Dense(1)(H) # output은 X가 아닌 H를 받는다
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [16]:
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
=================================================================
```
* 13개(X)의 입력으로 10개(H)의 출력을 만든다
* 10개의 입력으로 1개(Y)의 출력을 만든다
* Param : 가중치
* Param이 14(13개의 input, 1개의 bias) * 10 (hidden layer node가 10개)
* Param이 11(10개의 input, 1개의 bias)

In [15]:
model.fit(idp, dp, epochs = 1000, verbose=0)
model.fit(idp, dp, epochs = 10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 11.0314
Epoch 2/10
16/16 [==============================] - 0s 964us/step - loss: 10.5742
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 10.1709
Epoch 4/10
16/16 [==============================] - 0s 952us/step - loss: 11.0448
Epoch 5/10
16/16 [==============================] - 0s 959us/step - loss: 9.6625
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 11.6272
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 10.6917
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 10.5547
Epoch 9/10
16/16 [==============================] - 0s 982us/step - loss: 10.4815
Epoch 10/10
16/16 [==============================] - 0s 944us/step - loss: 11.4073


In [17]:
# 4. model 이용하기
print(model.predict(idp[:5]))
print(dp[:5])

[[30.250547]
 [20.89725 ]
 [32.592636]
 [33.39221 ]
 [31.338923]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


### 아이리스 품종분류

In [21]:
# 1. 과거의 데이터 준비
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(iris_path)

# one hot encoding
iris = pd.get_dummies(iris)

# 종속변수, 독립변수
iris_idp = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
iris_dp = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(iris_idp.shape, iris_dp.shape)

(150, 4) (150, 3)


In [28]:
# 2. model의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')
model.summary()

Model: "functional_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_14 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [25]:
# 3. 데이터로 모델 FIT 시키기
model.fit(iris_idp, iris_dp, epochs=100, verbose=0)
model.fit(iris_idp, iris_dp, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0577 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0647 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0608 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0577 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0642 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0585 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0578 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0593 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0616 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0698 - accuracy: 0.9667


In [27]:
# 4. model 이용하기
print(model.predict(iris_idp[0:5]))
print(iris_dp[0:5])

[[9.9999952e-01 4.2329557e-07 5.3968857e-13]
 [9.9999511e-01 4.8303200e-06 1.6025205e-11]
 [9.9999821e-01 1.7400570e-06 6.1508780e-12]
 [9.9999070e-01 9.3211993e-06 5.7278415e-11]
 [9.9999964e-01 3.4133052e-07 4.7603745e-13]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
